[package]
name = "tauri-plugin-global-shortcut"
version = "2.3.1"
description = "Register global hotkeys listeners on your Tauri application."
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
links = "tauri-plugin-global-shortcut"

[package.metadata.platforms.support]
windows = { level = "full", notes = "" }
linux = { level = "full", notes = "" }
macos = { level = "full", notes = "" }
android = { level = "none", notes = "" }
ios = { level = "none", notes = "" }
openharmony = { level = "partial", notes = "Requires API 14+. Max 2 modifiers. Wearable not supported." }

[build-dependencies]
tauri-plugin = { workspace = true, features = ["build"] }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tauri = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\", target_env = \"ohos\")))".dependencies]
global-hotkey = { version = "0.7", features = ["serde"] }

[target.'cfg(target_env = "ohos")'.dependencies]
openharmony-ability = { path = "../../../openharmony-ability/crates/ability", features = ["global_shortcut"] }
