#!/usr/bin/env bash
# Build libsodium for OHOS targets.
# Usage: bash scripts/build-libsodium-ohos.sh [target...]
# target: aarch64-linux-ohos | armv7-linux-ohos | x86_64-linux-ohos (default: all)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(dirname "$SCRIPT_DIR")"
NATIVE_DIR="$PLUGIN_DIR/native/ohos"

VERSION="1.0.20-stable"
TARBALL="libsodium-${VERSION}.tar.gz"
URL="https://download.libsodium.org/libsodium/releases/${TARBALL}"

# Validate OHOS_NDK_HOME
if [[ -z "${OHOS_NDK_HOME:-}" ]]; then
  echo "ERROR: OHOS_NDK_HOME not set" >&2
  exit 1
fi

CLANG="${OHOS_NDK_HOME}/native/llvm/bin/clang"
SYSROOT="${OHOS_NDK_HOME}/native/sysroot"
AR="${OHOS_NDK_HOME}/native/llvm/bin/llvm-ar"

if [[ ! -x "$CLANG" ]]; then
  echo "ERROR: clang not found at $CLANG" >&2
  exit 1
fi

build_target() {
  local triple="$1"
  local out_dir="$NATIVE_DIR/$triple"
  local build_dir
  build_dir=$(mktemp -d)

  echo "=== Building libsodium for $triple ==="

  # Use cached LATEST.tar.gz from libsodium-sys-stable crate (avoid network download)
  CACHED_TARBALL="/c/Users/65468/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libsodium-sys-stable-1.24.0/LATEST.tar.gz"
  if [[ -f "$CACHED_TARBALL" ]]; then
    echo "Using cached libsodium source: $CACHED_TARBALL"
    cp "$CACHED_TARBALL" "$build_dir/$TARBALL"
  else
    curl --ssl-no-revoke --retry 3 --retry-delay 5 -L -o "$build_dir/$TARBALL" "$URL"
  fi
  tar -xzf "$build_dir/$TARBALL" -C "$build_dir"

  local src_dir
  src_dir=$(find "$build_dir" -maxdepth 1 -name "libsodium-*" -type d | head -1)

  cd "$src_dir"

  # Restrict PATH to avoid C:/Program Files/... (spaces cause "C:/Program: No such file")
  # Create ld wrapper (configure expects 'ld', NDK has 'ld.lld')
  local tool_wrap make_bin
  tool_wrap=$(mktemp -d)
  cp "${OHOS_NDK_HOME}/native/llvm/bin/ld.lld.exe" "$tool_wrap/ld.exe"
  make_bin=$(dirname "$(which make 2>/dev/null)" 2>/dev/null)
  export PATH="$tool_wrap:/usr/bin:/bin:${OHOS_NDK_HOME}/native/llvm/bin:${make_bin:-}"

  export CC="$CLANG"
  export CFLAGS="--target=$triple --sysroot=$SYSROOT -D__MUSL__"
  export AR="$AR"
  export NM="${OHOS_NDK_HOME}/native/llvm/bin/llvm-nm"
  export SED="/usr/bin/sed"
  export GREP="/usr/bin/grep"

  ./configure \
    --host="$triple" \
    CC="$CLANG" \
    AR="$AR" \
    NM="$NM" \
    --enable-minimal \
    --disable-shared \
    --disable-pie \
    --disable-dependency-tracking \
    --prefix="$out_dir"

  make -j"$(nproc)"
  make install

  echo "=== libsodium.a built at $out_dir/lib/libsodium.a ==="

  # Workaround: libsodium-sys-stable build.rs 的 find_libsodium_env() 用
  # cfg!(target_env = "msvc") 判断库名,但 build.rs 编译运行在 HOST(Windows msvc),
  # cfg! 反映 host 而非 target。从 Windows host 交叉编译到 OHOS(linux)时 cfg!(msvc)=true
  # (误判),输出 rustc-link-lib=static=libsodium → rustc 找 liblibsodium.a;
  # 而 make install 生成的是 libsodium.a(对应 name="sodium")。提供一份 liblibsodium.a
  # 副本满足链接器查找,避免 "could not find native static library libsodium"。
  # 1.22.3/1.24.0 均有此上游行为(非版本漂移);见 tauri/openspec/stronghold-ohos-fix-plan.md。
  cp "$out_dir/lib/libsodium.a" "$out_dir/lib/liblibsodium.a"

  if command -v llvm-readelf &>/dev/null; then
    llvm-readelf -h "$out_dir/lib/libsodium.a" 2>/dev/null | grep -E "Machine:" || true
  fi

  cd - > /dev/null
  rm -rf "$build_dir"
  # NOTE: keep build_dir for debugging if make fails
}

generate_env_sh() {
  local env_sh="$SCRIPT_DIR/env.sh"
  cat > "$env_sh" << 'ENVEOF'
#!/usr/bin/env bash
# Auto-generated by build-libsodium-ohos.sh
# Source this before building stronghold for OHOS: source scripts/env.sh

if [[ -n "${CARGO_CFG_TARGET_ARCH:-}" ]]; then
  case "$CARGO_CFG_TARGET_ARCH" in
    aarch64) _triple="aarch64-linux-ohos" ;;
    armv7) _triple="armv7-linux-ohos" ;;
    x86_64) _triple="x86_64-linux-ohos" ;;
    *) _triple="aarch64-linux-ohos" ;;
  esac
else
  _triple="aarch64-linux-ohos"
fi

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_PLUGIN_DIR="$(dirname "$_SCRIPT_DIR")"
export SODIUM_LIB_DIR="$_PLUGIN_DIR/native/ohos/$_triple/lib"
echo "[env.sh] SODIUM_LIB_DIR=$SODIUM_LIB_DIR"
ENVEOF
  chmod +x "$env_sh"
  echo "=== Generated $env_sh ==="
}

# Main
if [[ $# -eq 0 ]]; then
  TARGETS=(aarch64-linux-ohos armv7-linux-ohos x86_64-linux-ohos)
else
  TARGETS=("$@")
fi

for target in "${TARGETS[@]}"; do
  build_target "$target"
done

generate_env_sh

echo "=== Done. Run 'source scripts/env.sh' before building stronghold for OHOS. ==="
