#!/usr/bin/env bash
# Auto-generated by build-libsodium-ohos.sh
# Source this before building stronghold for OHOS: source scripts/env.sh

if [[ -n "${CARGO_CFG_TARGET_ARCH:-}" ]]; then
  case "$CARGO_CFG_TARGET_ARCH" in
    aarch64) _triple="aarch64-linux-ohos" ;;
    armv7) _triple="armv7-linux-ohos" ;;
    x86_64) _triple="x86_64-linux-ohos" ;;
    *) _triple="aarch64-linux-ohos" ;;
  esac
else
  _triple="aarch64-linux-ohos"
fi

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_PLUGIN_DIR="$(dirname "$_SCRIPT_DIR")"
export SODIUM_LIB_DIR="$_PLUGIN_DIR/native/ohos/$_triple/lib"
echo "[env.sh] SODIUM_LIB_DIR=$SODIUM_LIB_DIR"
